spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wfb911228
    url: jdbc:mysql://localhost:3306/vhr2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.1.230
    database: 0
    port: 6379
    password: ''
  cache:
    cache-names: menus_cache
server:
  port: 8089
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/